### ISSUE TITLE
Add build ignore command

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#156]
# Angular App version

- [ ] `angular-v16` - has no UI libraries
- [ ] `angular-v16-AnguMAT` - has Angular Material
- [ ] `angular-v16-PrimeNG` - has PrimeNG 
- [ ] `angular-v17` - has no UI libraries
- [ ] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG 
- [ ] `angular-hashnode`- presentation site

**Additional context**
figure out how to ignore builds not related to the project where the changes were made

**Comment by cleancodecraft** [comment]
@monacodelisa  this needs exploration I will be looking into it
