### ISSUE TITLE
Retrieve, style and display blog posts v17 Angular Material

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#178]
# Angular App version

- [ ] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [x] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG 
- [ ] `angular-hashnode`- presentation site

## Following the structure of either `angular-v17` or `angular-v17-AnguMAT`
- add a component to display all posts
- set up dynamic routing to lead you to the correct post matching by post `slug` 
- style the posts and post image

- # awaiting #52

**Comment by yshashi** [comment]
Hey just wanted to confirm, that we are not looking for the same UI that we have built for the v17 native one.
All we need is to use the material components, correct?

Also how about doing some cosmetic changes, so still we are allowed to use the scss?

**Comment by monacodelisa** [comment]
> Hey just wanted to confirm, that we are not looking for the same UI that we have built for the v17 native one. All we need is to use the material components, correct?
> 
> Also how about doing some cosmetic changes, so still we are allowed to use the scss?

Yes the main idea is to utilize the existing angular material components but of course custom scss is usually added since they are not perfect. The only important thing is to keep the `theme.scss` file only related to colors - any styling of elements that needs different colors for light and dark - needs to be done in the `theme.scss`. 

Other than that you have the freedom to adjust try, use the global `style.scss` for repeating styles, and components for small style adjustments. There isn't a set design - it's actually better to see different versions, different layouts and maybe later on it can be made similar, or it may remain a bit different to offer a bit of variety.
