### ISSUE TITLE
Query the actual series (topics) to display in header in v17 angumat

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#215]
# Angular App version

- [ ] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [x] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG

**Additional context**
Right now we have placeholder object in header with some sample series,
instead - we need to connect to the real ones using the blog service and another query for blog series

- and of course remove the placeholder object array from the header

Implementation is similar to how the social links are retrieved, if there are questions do not hesitate to ask

**Comment by cleancodecraft** [comment]
@monacodelisa can I help in this one please ?

**Comment by monacodelisa** [comment]
> @monacodelisa can I help in this one please ?

Sure :)

**Comment by cleancodecraft** [comment]
Actually I will be a bit delayed

**Comment by monacodelisa** [comment]
@cleancodecraft no worries I got it going
