### ISSUE TITLE
Add pagination - at some point pagination is to be added starting with v17 native (for example)

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#222]
# Angular App version

- [x] `angular-v17` - has no UI libraries
- [ ] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG

**Additional context**
Right now the existing blog query is retrieving the first 10 blog posts, this is the initial state to get things going.
A pagination needs to be implemented that when the user navigates to the next page a different query is used to retrieve the next 10 posts and the next and so on.

In the query this is done by specifying `after 10`  I believe.

**Comment by cleancodecraft** [comment]
can I just add a paginator element ?

**Comment by monacodelisa** [comment]
> can I just add a paginator element ?

@cleancodecraft if you are going to work on this issue it makes sense to follow the requirements, and since this is the version without UI libraries if you are devoting time to the paginator element it makes sense to also just add a click event and handle the next page ? 

you could make a paginator component if you like

**Comment by cleancodecraft** [comment]
> > can I just add a paginator element ?
> 
> @cleancodecraft if you are going to work on this issue it makes sense to follow the requirements, and since this is the version without UI libraries if you are devoting time to the paginator element it makes sense to also just add a click event and handle the next page ?
> 
> you could make a paginator component if you like

ok good idea thank you

**Comment by jhonacs2** [comment]
@cleancodecraft Are you working on this feature? watching hashnode is weighing adding the load more component and the infinity scroll to load the blogs.

**Comment by cleancodecraft** [comment]
@jhonacs2 the project has moved to a GitHub organization -> [HashnodeNG](https://github.com/HashnodeNG)
Issues need to be transferred - copied first before anyone works on them, I will be copying some issues and then I can assign you

**Comment by cleancodecraft** [comment]
@jhonacs2 you are more than welcome to transfer some issues too - maybe just copy this one and start working on it because it will take me a wile to write them all
