### ISSUE TITLE
Create an Angular v17 app and add Angular Material

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#24]
**Is your feature request related to a problem? Please describe.**
Angular v17 app needed (in the root directory of the project) set to use Angular Material

**Describe the solution you'd like**
app name to be `angular-v17-AnguMAT`

My [YouTube video showing how to do it](https://www.youtube.com/watch?v=JYbn1Q25EEc)

**Comment by Ali7040** [comment]
@monacodelisa Hi there! I want to contribute to your project. Is there any issue for me?

**Comment by monacodelisa** [comment]
> @monacodelisa Hi there! I want to contribute to your project. Is there any issue for me?

of course, you are welcome to come along - have a look at the existing open issues, if you are looking for something more specific let me know and I can try and find you something matching
