### ISSUE TITLE
Add a pop-up dialog for the follow button v17 AnguMAT

### ISSUE THREAD

**Issue by cleancodecraft** [monacodelisa/Angular-Headless-Hashnode#248]
# Angular App version

- [ ] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [x] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG

**Additional context**

UPDATE - following the blog still has to be done only through hashnpde so a dialog opening up on click might be the way to go for now, this is what happens on hashnode when we click the follow button 

![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/64324417/da44c9f0-4797-421e-9732-e9b0985fe93c)

on click going to - https://hashnode.com/ to sign in

**Comment by cleancodecraft** [comment]
@Ali7040 are you working on this? because I have the code for it ready

**Comment by Ali7040** [comment]
@cleancodecraft Yes, but if you have a code, go for it.

**Comment by cleancodecraft** [comment]
> @cleancodecraft Yes, but if you have a code, go for it.

thank you very much

**Comment by Ali7040** [comment]
@cleancodecraft Actually, I am facing an issue when I try to run the 'ng serve' command. It started happening when I pulled the latest changes."

**Comment by cleancodecraft** [comment]
> @cleancodecraft Actually, I am facing an issue when I try to run the 'ng serve' command. It started happening when I pulled the latest changes.

give more details maybe I can help ?

**Comment by Ali7040** [comment]
> > @cleancodecraft Actually, I am facing an issue when I try to run the 'ng serve' command. It started happening when I pulled the latest changes.
> 
> @Ali7040 give more details maybe I can help ?

@cleancodecraft I recently started a discussion. You can check all the details there, and we can discuss the issue.

**Comment by cleancodecraft** [comment]
@monacodelisa please take it over
