### ISSUE TITLE
Change CSS to SCSS in angular-v17 and v17-PrimeNG and px to relative rem

### ISSUE THREAD

**Issue by cleancodecraft** [monacodelisa/Angular-Headless-Hashnode#252]
# Angular App version

- [x] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [ ] `angular-v17-AnguMAT` - has Angular Material
- [x] `angular-v17-PrimeNG` - has PrimeNG

**Additional context**
The project is obviously using `scss` and relative measurements `rem` so styling should be adjusted ascordingly
- use `scss` format
- use `rem` not `px`

**Comment by monacodelisa** [comment]
@cleancodecraft it is true that someone swooped in some CSS but there is no need to call it messy ;)

**Comment by cleancodecraft** [comment]
> @cleancodecraft it is true that someone swooped in some CSS and `px` measurements, but there is no need to call it messy, it is better to just fix it

ok, understood 👍
