### ISSUE TITLE
Align the icon an the text of the tags in post-details in v17 PrimeNG

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#276]
# Angular App version

- [ ] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [ ] `angular-v17-AnguMAT` - has Angular Material
- [x] `angular-v17-PrimeNG` - has PrimeNG

**Is your feature request related to a problem? Please describe.**
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/64324417/1f90f3ab-61eb-4797-8a1d-77f5af08957b)

**Describe the solution you'd like**
the text and the icon must be aligned like this: 
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/64324417/a777b5c5-20e9-45e1-b8b7-a63062dd0c3b)

**Comment by dobanisola-scottlogic** [comment]
Hi, this is my first time contributing here and I'll like to be assigned this issue. Thanks

**Comment by ojuolarpe** [comment]
Hi, this is my first time contributing here and I'll like to be assigned this issue. Thanks

**Comment by monacodelisa** [comment]
@ojuolarpe you are assigned :) if you have any questions or need assistance just ask 👍

**Comment by ojuolarpe** [comment]
Thanks @monacodelisa. I tried to reproduce the bug but couldn't. I ran the Primeng project and saw that the text is well-aligned. Is there something I am missing.

<img width="485" alt="image" src="https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/30655876/2de91d04-2283-46e7-8efa-0e5ae8fb27b7">

**Comment by monacodelisa** [comment]
@ojuolarpe I did some global style changes to all of the project versions - changing the layout, so the problem most probably was that a style was applied but it was not picking up. It does appear correct now.

Have a look at some of the other issues and pick something that you like, or - if you notice something that is not working or looking right - you can write your own issue - I will send you an invitation to collaborate and you will se i t shortly on the project's page

**Comment by monacodelisa** [comment]
@ojuolarpe 

![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/64324417/122dad5f-916f-4ae5-96d6-b5e31eeebaa8)

**Comment by monacodelisa** [comment]
solved with PR #355
