### ISSUE TITLE
Query the blog 'favicon' or 'logo' or 'author image' in header in v17 native

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#280]
# Angular App version

- [x] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [ ] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG

**Is your feature request related to a problem? Please describe.**
In the header in the logo - right now the image of the project is loaded and as we discussed 
the intension is to use the image for the actual blog of whoever is using the app. 

**Describe the solution you'd like**
So there are few possible ways to do this:
- first perform check if there is a `favicon` is yes - use it
- if no favicon, then check for publication logo
- if no logo then query author image

**Additional context**
Requires a slight addition to the already existing blog info query 

edit by @cleancodecraft 
# adding screenshots to every issue is not a common practice in open source, 
- reading the description, 
- looking at the lables 
- asking question BEFORE submitting a PR is the responsibility of the contributor 

This is what this written above

# `Requires a slight addition to the already existing blog info query ` - if you do not understand what it means then maybe don't say you have closed the issue ?

![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/132580309/332ef9ba-d28e-4a14-b456-a70991bc8cc9)

The image to be replaced 

![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/132580309/b8044c19-1ee7-424b-b650-c3428a0bc972)

**Comment by cleancodecraft** [comment]
@jhonacs2 when you read the description is the word `favicon` the only part that you understand? 
Did you happen to see the words header, logo image, or maybe the labels 'appolo angular', `graphql`
or the part where it says to perform checks ?

**Comment by cleancodecraft** [comment]
@jhonacs2 I will add a different issue that actually describes your PR
