### ISSUE TITLE
Animation and border-radius for Post card components in Angular-v17-anguMAT.

### ISSUE THREAD

**Issue by Ali7040** [monacodelisa/Angular-Headless-Hashnode#286]
# Angular App version

- [ ] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [x] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG

## Animation on Hover
 When a user hovers over the card, there should be an animation effect.
## Border-Radius
The corners of the cards should have a border radius, giving them a rounded appearance.

**Comment by monacodelisa** [comment]
sounds good 👍
