### ISSUE TITLE
Create series component to load series posts matched by route v17 AnguMAT

### ISSUE THREAD

**Issue by Ali7040** [monacodelisa/Angular-Headless-Hashnode#287]
# Angular App version

- [ ] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [x] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG 

**Describe the bug**
When the user clicks on a series (topic), it shows an empty page, and errors are logged in the console. There is an issue with the routing.

**Comment by Ali7040** [comment]
I would like to work on that issue.

**Comment by monacodelisa** [comment]
This is a duplicate an issue for it exists, you can work on it just mark the correct one as completed

**Comment by monacodelisa** [comment]
I'm not on the computer, if I find a duplicate I will add a comment tomorrow, but yes it's great that you are writing the issues 👍 keep it up and work on this one

**Comment by Ali7040** [comment]
> @Ali7040 I'm not on the computer, if I find a duplicate I will add a comment tomorrow, but yes it's great that you are writing the issues 👍 keep it up and work on this one

hanks for appreciating. That means a lot to me.

**Comment by monacodelisa** [comment]
@Ali7040 ok I found it, have a look at #221, to implement the routing you will need to create the `series` component, this has not been done yet for the AnguMAT app version so it is a feature

**Comment by cleancodecraft** [comment]
@Ali7040 I hope that the project is working fine for you now, if you have any issues just share like before, we are here to help
