### ISSUE TITLE
Implement theme switching using Angular Signals and Angular Material in v17

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#29]
# Angular App version

- [ ] `angular-v16` - has no UI libraries
- [ ] `angular-v16-AnguMAT` - has Angular Material
- [ ] `angular-v16-PrimeNG` - has PrimeNG 
- [ ] `angular-v17` - has no UI libraries
- [x] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG 
- [ ] `angular-hashnode`- presentation site

**Is your feature request related to a problem? Please describe.**
The ability to switch between dark and light mode is to be implemented

**Describe the solution you'd like**
A theme service using signals and `[ngClass]` or just `[class]` in v17.2

**Additional context**
My [YouTube video showing how to do it](https://www.youtube.com/watch?v=JYbn1Q25EEc)

- implement matching structure to v16 with angular material
- use mat toolbar in the header component
- use mat slide toggle & mat icons with `@if` statement
- use theme service and signals
- use "dark" and "light" class names
- use `[class]` connected to the signal in `app.component.html`

**Comment by Ali7040** [comment]
Assign it to me; I want to work on it.

**Comment by monacodelisa** [comment]
> Assign it to me; I want to work on it.

@Ali7040 ok I have assigned you to this one 👍

**Comment by monacodelisa** [comment]
> Assign it to me; I want to work on it.

@Ali7040 ok let me just start up the app and I will assign you this one

**Comment by monacodelisa** [comment]
@Ali7040 you have been assigned, basic layout for the app is created you can go ahead

**Comment by Ali7040** [comment]
@monacodelisa Great! Thanks for assigning

**Comment by monacodelisa** [comment]
@Ali7040 I saw your branch on the forked repo and you are working on the wrong app version 
there is a designated app for each version, if the app name does not mention "AnguMAT" then this app is not meant to have Angular Material.

![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/64324417/d360b731-1a61-4a37-93d6-62c89e2e9f39)

I created the `angular-v17-AnguMAT` before I assigned the issue to you.
what you need to do is to pull all the lates changes from the 'develop' branch and you will see the correct app

**Comment by monacodelisa** [comment]
> @monacodelisa so I need to work on angular-v17-anguMat. Right?

Yes, correct. When you open `angular-v17-anguMAT` you will see that angular material is added but there is no theme service, no signals, the header is empty - needs a mat-toolbar, toggle button, mat icons and then the theme switching functionality

**Comment by Ali7040** [comment]
I've got it. There isn't even a navbar.

**Comment by cleancodecraft** [comment]
can I work on this feature ? it will take me 10 min at most

**Comment by monacodelisa** [comment]
> can I work on this feature ? it will take me 10 min at most, I prefer that there is no toolbar, I don't want to just change a set of brackets and call it a day ;)

we are going to give @Ali7040 one more day since he showed initial interest

**Comment by cleancodecraft** [comment]
ok

> > can I work on this feature ? it will take me 10 min at most, I prefer that there is no toolbar, I don't want to just change a set of brackets and call it a day ;)
> 
> we are going to give @Ali7040 one more day since he showed initial interest

ok

**Comment by Ali7040** [comment]
please check PR.

**Comment by Ali7040** [comment]
@monacodelisa I just implement the theme toggle next provide me a guide for header compoenet I am ready to work on it

**Comment by monacodelisa** [comment]
@Ali7040 I have sent you an invitation to join as a collaborator, you should see it when you go to the homepage of the project - [project home page](https://github.com/monacodelisa/angular-headless-hashnode).

I created a new issue(feature) for you #146, if you do not see the invitation just comment on issue #146 so I can assign it to you
