### ISSUE TITLE
Style links and images in `post-details` in angular-v17

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#296]
# Angular App version

- [x] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [ ] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG

**Describe the solution you'd like**
We need to be able to visually identify links
- links should have a slightly lighter color then the rest of the text in dark mode (same colors as used for global links styling)
- links should have a slightly darker color then the rest of the text in light mode (same colors as used for global links styling)
- for dark mode maybe the `p` element's color can be made one idea darker so the links stand out more
- remove extra space coming from the global styles on `a` elements

Images within the blog post should be center aligned 

what it is now:
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/64324417/0b8bcff1-816e-49a6-9806-ba30ed6aecb0)

what should be (more or less) 
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/64324417/34b87f02-7e03-41b8-ba46-6eb2c457aa05)

**Comment by jhonacs2** [comment]
@monacodelisa I'm working on the links part and on the content part, I'm returning the decoration of the text, without affecting the other links, what do you think of the idea? In the event that we have the decoration text, is it necessary for us to have the text a little clearer? Or dark depending on the theme.
What do you think? 
If it is decided that the text decoration is not there, I will continue with the idea of ​​the link text being lighter or darker, there is no problem 😁
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/75391330/69ec2ac6-15b4-4600-817d-96f2f0784cc3)
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/75391330/93a59c5f-cfed-487d-8668-763c78510701)

**Comment by monacodelisa** [comment]
@jhonacs2 I was thinking either that... or maybe using an accent color, maybe accent color for the `PrimeNG` version, and/or `angular material` versions 

for this version - yes keep going like this looks good 👍
