### ISSUE TITLE
Implement HTML Sanitizer

### ISSUE THREAD

**Issue by jhonacs2** [monacodelisa/Angular-Headless-Hashnode#306]
# Angular App version

- [x] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [ ] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG

**Describe the solution you'd like**
Implement an HTML sanitizer in our application to mitigate XSS vulnerabilities. This sanitizer would effectively filter and clean HTML content, removing any potentially harmful elements and attributes.

**Comment by monacodelisa** [comment]
@jhonacs2 good call 👍
