### ISSUE TITLE
Post card title is overflowing on posts component angular-v17-PrimeNG

### ISSUE THREAD

**Issue by czBalazs98** [monacodelisa/Angular-Headless-Hashnode#327]
# Angular App version

- [ ] `angular-v17` - has no UI libraries
- [ ] `angular-v17-modMAT` - modules and Angular Material
- [ ] `angular-v17-AnguMAT` - has Angular Material
- [x] `angular-v17-PrimeNG` - has PrimeNG 

Post card title is overflowing on posts component.

**Comment by monacodelisa** [comment]
@czBalazs98 sounds good will take care of the PR shortly, can you share a screenshot because I am really not sure which overflow, I would like to see it

**Comment by czBalazs98** [comment]
Screenshot:
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/53296597/eb517564-87f1-43d0-aeed-2cb966f6486e)

**Comment by monacodelisa** [comment]
very interesting, you don't see 3 columns like this:
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/64324417/84db97b5-ead3-4f57-bc22-13fc5348dedf)

**Comment by monacodelisa** [comment]
@czBalazs98 is that a view on a tablet or phone or some other mobile device ?

**Comment by monacodelisa** [comment]
@czBalazs98 yes that is related to responsiveness, which has not been covered due to more pressing issues, but will add a label and merge it, more context always helps 👍

**Comment by monacodelisa** [comment]
@czBalazs98 that actually creates another issue:

![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/64324417/0b1365a8-a46b-464c-996b-c8f0f11baddf)

which is why I had set the height to a specific value. I suggest to handle this with a `media query` where we target the relevant devices, and add specific styles like it's usually done when it comes to responsive design

**Comment by czBalazs98** [comment]
what case this issue appears?

**Comment by cleancodecraft** [comment]
@czBalazs98 this issue appears when you apply the changes that you have set in this PR, once you remove the set height of the `p-card-title` and add `height: 100%` to the <p-card>` element, the `<p-card>` element takes a much height as here is content inside if it, so longer titles will cause the `p-card-title` to get a height increase, while shorter titles will decrease the height and that increases the overall height of the `<p-card>` element.

**Comment by czBalazs98** [comment]
You can check the deploy preview on the pr, it looks good there too

**Comment by czBalazs98** [comment]
> @czBalazs98 yes that is related to responsiveness, which has not been covered due to more pressing issues, I will add a label, more context always helps 👍

I don't think it's a responsiveness problem if it appears on notebook screens. In my opinion a web page should always be nicely visible on a notebook without a monitor. Mobiles, tablets, screen-readers are a different topic, they need different layoutings, which involves using of the responsive tools offered by css, but I don't think a notebook screen should be handled differently. For example in TailwindCSS css framework responsivity options, the xl size is way less in width than a simple notebook screen's size.

**Comment by cleancodecraft** [comment]
@czBalazs98 in your PR you are removing the set height of the `p-card-title`

![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/132580309/21d77283-e74a-446c-9bce-cba25c6b8a1c)

this is what is causing an issue, setting `p-card` height to `100%` on it's own doesn't do anything. Notebook is a specific type of devise - making the site look nicely on Notebook is adding responsiveness. What is the resolution of your Notebook screen ?

**Comment by czBalazs98** [comment]
don't really understand your point, this is the result of .p-card set to auto, which is the default option if the height is not set I just set it for an easier explanation:
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/53296597/40ef495c-5d45-4e7b-8abb-b9620888a575)
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/53296597/863962c8-20f7-470d-b8e7-792b3fe88a09)

and this is the result of .p-card height set to 100%
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/53296597/59354d29-5579-4469-991c-779cc887b39d)
![image](https://github.com/monacodelisa/Angular-Headless-Hashnode/assets/53296597/ca602d64-aaaf-453f-ad77-5a17d8295b25)

Netlify creates a preview deployment of my pr, you can check that here: https://deploy-preview-328--angular-v17-primeng.netlify.app/

**Comment by monacodelisa** [comment]
@cleancodecraft @czBalazs98 I approved and I am going to merge, but please maybe in the future instead of devoting so much efforts on something that is not a pressing issue, and involves few lines of code change, we can focus on the rest of the already existing issues ? Right now - whether I merge or not - there really isn't a huge difference to the project while so much is not yet implemented. There are over 40 issues that require a bit more significant change, let's have a look at them first before divining into deep discussions please 🙏
