### ISSUE TITLE
Setup Angular Routing in v17 native

### ISSUE THREAD

**Issue by monacodelisa** [monacodelisa/Angular-Headless-Hashnode#49]
# Angular App version

- [ ] `angular-v16` - has no UI libraries
- [ ] `angular-v16-AnguMAT` - has Angular Material
- [ ] `angular-v16-PrimeNG` - has PrimeNG 
- [x] `angular-v17` - has no UI libraries
- [ ] `angular-v17-AnguMAT` - has Angular Material
- [ ] `angular-v17-PrimeNG` - has PrimeNG 
- [ ] `angular-hashnode`- presentation site

**Is your feature request related to a problem? Please describe.**
Routing needs to be implemented

**Describe the solution you'd like**
Use Angular Routing

**Additional context**
in v17 use the `app.routes.ts` file
My [YouTube video](https://www.youtube.com/watch?v=HSkP1bD96n0) showing how to do it

**Comment by monacodelisa** [comment]
@Ali7040 this has been completed please do not work on this

**Comment by Ali7040** [comment]
> @Ali7040 this has been completed please do not work on this, please when you see an issue that has been completed just mark as completed, you can still self assign 

Okay got it.
